---
title: "04-CTA1-induction"
author: "JY"
date: "11/9/2022"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggprism)
library(dplyr)
library(mgcv)
library(broom)
library(cowplot)
```
# read the Cta1-GFP induction in different conditions
```{r}
cta1 <- read.csv("./input/Long_data_CTA1-GFP.csv")

# arrange data with different treatment
pi.dat <- cta1 %>% 
  mutate(`Time (min)` = Time) %>% 
  mutate(new_median =median) %>% 
  mutate(new_time = as.numeric(gsub("min","",Time)))%>% 
  arrange(new_time, Treatment)

pi.dat.summary <- pi.dat %>% 
  filter(!is.na(new_median)) %>%
  group_by(Treatment,Time) %>% 
  summarise(sd = sd(new_median, na.rm = TRUE), mean_median = mean(new_median)) %>% 
  mutate(.,new_time = as.numeric(gsub("min","",Time)))


```


# Common plotting elements
```{r}
p.timecourse <- list(
  stat_summary(fun = "mean", geom = "point", size = 3),
  stat_summary(fun.data = "mean_cl_boot", geom = "errorbar", width = 3),
  stat_smooth(aes(size = Treatment == "Control"), se = FALSE),
  scale_x_continuous(breaks = seq(0,240,30)),
  scale_size_manual(values = c(0.8, 1.5), guide = "none"),
  labs(y = "Cta1-GFP protein level (a.u.)"),
  theme_cowplot(line_size = 0.7),
  theme(legend.position=c(0.05,0.9), 
        #legend.box.background = element_rect(color = "black"),
        #legend.box.margin = margin(3,3,3,3),
        legend.text = element_text(face = 3), 
        legend.title = element_text(),
        axis.title = element_text(size = rel(1)), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(hjust=0.5), axis.text = element_text(size = rel(1)),
  )
)
```

```{r, set up plot}
Treatment_color <- RColorBrewer::brewer.pal(8, "Dark2")[c(8, 3, 7)] 
names(Treatment_color) <- c("0mM Pi", "Control", "2mM H2O2")

pi.dat %>%
  filter(!is.na(new_median)) %>% 
  ggplot(aes(x = new_time, y = new_median, color = Treatment)) + p.timecourse +
  scale_color_manual(values= Treatment_color)
  ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-Cta1-GFP-induction.png"),
         width = 5, height = 5,units = 'in', dpi = 300)
```