---
title: "Fig4"
author: "JY"
date: "10/25/2022"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(mgcv)
library(broom)
```



```{r, Import the Data into R}
files <- dir("input/msn24_gz_merge", pattern = "merge-*") # get the file names of the merged
files <- file.path("input/msn24_gz_merge", files)         # this appends the directory to the file names
files.s7y1 <- dir("input/s7y1_gz_merge", pattern = "merge-*") 
files.s7y1 <- file.path("input/s7y1_gz_merge", files.s7y1)  
files.m4s7 <- dir("input/m4s7_gz_merge", pattern = "merge-*") 
files.m4s7 <- file.path("input/m4s7_gz_merge", files.m4s7)


names(files) <- c("Rep1-0Pi-Ctrl","Rep2-0Pi-Rep1-H2O2", "Rep3-0Pi-Rep2-H2O2", "Rep3-H2O2-Ctrl","Rep4-H2O2-Ctrl")
names(files.s7y1) <- c("Rep1-0Pi-Ctrl","Rep2-0Pi-Ctrl","Rep1-H2O2-Rep3-0Pi", "Rep2-H2O2-Rep4-0Pi", "Rep3-H2O2-Ctrl")
names(files.m4s7) <- c("Rep1-0Pi-Ctrl","Rep1-H2O2-Rep2-0Pi", "Rep2-H2O2-Rep3-0Pi", "Rep3-H2O2-Ctrl")

tp <- c("0min",  "30min", "60min", "90min", "120min", "150min",  "180min", "210min", "240min") # ordered time points


      

# import and process the data to the format we want
dat.ord <- files %>% 
  map(~read_csv(., na = c("", "NA", "N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(`X Parameter` == "BL1-H", is.na(`Y Parameter`)) %>% 
  select(Replicate, Plate, Group, Sample, Count, median = `X Median`, peak = `X Peak`,
         sd = `X SD`, cv = `X %CV`, rCV = `X %rCV`) %>% 
  mutate(Group = ordered(Group, levels = tp)) %>% 
  arrange(Group)


# import and process the data to the format we want
dat.ord.s7y1 <- files.s7y1 %>% 
  map(~read_csv(., na = c("", "NA", "N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(`X Parameter` == "BL1-H", is.na(`Y Parameter`)) %>% 
  select(Replicate, Plate, Group, Sample, Count, median = `X Median`, peak = `X Peak`,
         sd = `X SD`, cv = `X %CV`, rCV = `X %rCV`) %>% 
  mutate(Group = ordered(Group, levels = tp)) %>% 
  arrange(Group)


# import and process the data to the format we want
dat.ord.m4s7 <- files.m4s7 %>% 
  map(~read_csv(., na = c("", "NA", "N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(`X Parameter` == "BL1-H", is.na(`Y Parameter`)) %>% 
  select(Replicate, Plate, Group, Sample, Count, median = `X Median`, peak = `X Peak`,
         sd = `X SD`, cv = `X %CV`, rCV = `X %rCV`) %>% 
  mutate(Group = ordered(Group, levels = tp)) %>% 
  arrange(Group)

```


```{r, Subset the dataset and merge with the genotype information:}
# get genotype info
tr_files <- dir("input/msn24_treatment", pattern = "d0*")
tr_files <- file.path("input/msn24_treatment", tr_files)
names(tr_files) <- c("Rep1-0Pi-Ctrl","Rep2-0Pi-Rep1-H2O2", "Rep3-0Pi-Rep2-H2O2", "Rep3-H2O2-Ctrl","Rep4-H2O2-Ctrl")

tr_files.s7y1 <- dir("input/s7y1_treatment", pattern = "d0*")
tr_files.s7y1 <- file.path("input/s7y1_treatment", tr_files.s7y1)
names(tr_files.s7y1) <- c("Rep1-0Pi-Ctrl","Rep2-0Pi-Ctrl","Rep1-H2O2-Rep3-0Pi", "Rep2-H2O2-Rep4-0Pi", "Rep3-H2O2-Ctrl")

tr_files.m4s7 <- dir("input/m4s7_treatment", pattern = "d0*")
tr_files.m4s7 <- file.path("input/m4s7_treatment", tr_files.m4s7)
names(tr_files.m4s7) <- c("Rep1-0Pi-Ctrl","Rep1-H2O2-Rep2-0Pi", "Rep2-H2O2-Rep3-0Pi", "Rep3-H2O2-Ctrl")


treat.fil <- tr_files %>% 
  map(~read_csv(., na = c("","NA","N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(!is.na(`group_name`)) %>% 
  select(Replicate, genotype = `group_name`, Sample, treat)


treat.fil.s7y1 <- tr_files.s7y1 %>% 
  map(~read_csv(., na = c("","NA","N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(!is.na(`group_name`)) %>% 
  select(Replicate, genotype = `group_name`, Sample, treat)


treat.fil.m4s7 <- tr_files.m4s7 %>% 
  map(~read_csv(., na = c("","NA","N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(!is.na(`group_name`)) %>% 
  select(Replicate, genotype = `group_name`, Sample, treat)


# combine genotype and treat variables into the flow data
data <- left_join(dat.ord, treat.fil, by = c("Replicate", "Sample"))
data.s7y1 <- left_join(dat.ord.s7y1, treat.fil.s7y1, by = c("Replicate", "Sample"))
data.m4s7 <- left_join(dat.ord.m4s7, treat.fil.m4s7, by = c("Replicate", "Sample"))


data.tmp <- add_row(data,data.s7y1)
data.cb <- add_row(data.tmp, data.m4s7)

# select out 0Pi data
pi.dat <- data.cb %>% 
  filter(treat == "0Pi" & !genotype %in% c("skn7yap1_ko","msn2msn4_ko")) %>%  
  select(Time = Group, Sample, Plate, replicate = Replicate, genotype, median) %>%
  mutate(.,Genotype = gsub("_ko","",genotype)) %>% 
  mutate(.,new_median =median/1000) %>% 
  mutate(.,new_time = as.numeric(gsub("min","",Time)))%>% 
  arrange(new_time, genotype, replicate)

pi.dat.summary <- pi.dat %>% 
  filter(!is.na(new_median)) %>%
  group_by(Genotype,Time) %>% 
  summarise(sd = sd(new_median, na.rm = TRUE), mean_median = mean(new_median)) %>% 
  mutate(.,new_time = as.numeric(gsub("min","",Time)))
  # ,new_time = new_time

# equivalent to !genotype %in% c("skn7yap1_ko","msn2msn4_ko") is: genotype != "skn7yap1_ko" & genotype !="msn2msn4_ko")
# cannot write as: genotype != c("skn7yap1_ko","msn2msn4_ko")

```


CTA1 induction during - Pi in wt/skn7/yap1/msn2/msn4/msn4skn7 strains
# need to check the skn7 and yap1 data, I got them switched somehow
```{r, visualize the data}
genotype_color <- c("#F8766D", "#00BFC4", "#00BA38", "#619CFF", "#E76BF3", "#B79F00") 
# map the color to the genotype variable within pi.dat in its order m2-m4-m4s7-s7-wt-y1
my_genotype <- c("wt", "msn2_ko", "msn4_ko","skn7_ko", "yap1_ko", "msn4skn7_ko")

pi.dat %>%# subset(., !is.na(new_median)) %>%  
  filter(!is.na(new_median)) %>% 
  ggplot(aes(x = new_time, y = new_median, color = Genotype)) + geom_point(size = 0.2) + 
  stat_summary(fun = "mean", geom = "point", size = 2) +
  stat_smooth(aes(x = new_time), se = FALSE) +
  scale_x_continuous(breaks = seq(0,240,30), minor_breaks = seq(0,240,30))+
  theme_bw() +
  theme(legend.position=c(0.15,0.72), legend.background = element_rect(fill = "white", color = "black", size = 1),
        legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=0,hjust=0.5), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values= genotype_color)
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-trans-TFs-kos.png"),
   #      width = 7, height = 4,units = 'in', dpi = 300)

#library(scales)
#show_col(hue_pal()(5))
#show_col(hue_pal()(6))

pi.dat.summary %>%
  ggplot(aes(x = new_time, y = mean_median, color = Genotype)) + geom_point(size = 0.5) + 
  geom_errorbar(aes(ymin=mean_median-sd, ymax=mean_median+sd), width=3, size = 0.8 ) +
  stat_summary(fun = "mean", geom = "point", size = 2) +
  stat_smooth(aes(x = new_time), se = FALSE) +
  scale_x_continuous(breaks = seq(0,240,30), minor_breaks = seq(0,240,30))+
  theme_bw() +
  theme(legend.position=c(0.18,0.75), legend.background = element_rect(fill = "white", color = "black", size = 1),
        legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=0,hjust=0.5), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values= genotype_color)
  ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-sd-trans-TFs-kos.png"),
         width = 7, height = 5,units = 'in', dpi = 300)  
  
  # position=position_dodge(0.5)
```
box plot + dot plot for trans TF kos CTA1-GFP
```{r}
pi.tp <- pi.dat %>% 
  filter(Time %in% c("0min", "240min" ) & !is.na(median))

pi.tp %>% 
  mutate(Genotype = factor(Genotype, levels = c("wt", "yap1", "msn2", "msn4", "skn7", "msn4skn7"))) %>% 
  ggplot(aes(x=Genotype, y=new_median, color = Time)) +
  geom_point(aes(x = Genotype, y = new_median), position = position_jitterdodge(jitter.width = 1)) +
  theme_bw() +
  theme(legend.position=c(0.9,0.85), legend.background = element_rect(fill = "white", color = "black", size = 1), legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=30,hjust = 1, vjust = 1), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  stat_summary(aes(group = Time), fun = "median", geom = "point", 
               color = "gray50", position = position_dodge()) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values = c("0min" = "#999999", "240min" = "#F564E3"))
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-TFs-kos-tp.png"),
   #      width = 10, height = 5,units = 'in', dpi = 300)
  

#library(scales)
#show_col(hue_pal()(5))
#show_col(hue_pal()(6))
```

#Internal removal/overlaping (OL) variants
```{r, Import the Data into R}
files.OL <- dir("input/OL_csv_merge", pattern = "d01*") # get the file names of the merged
files.OL <- file.path("input/OL_csv_merge", files.OL)         # this appends the directory to the file names

names(files.OL) <- c("Rep1-0Pi","Rep2-0Pi", "Rep3-0Pi")

tp <- c("0min", "30min", "60min", "90min", "120min", "150min",  "180min", "210min", "240min") # ordered time points

# import and process the data to the format we want
## remove characters (0Pi-0min; 240mmin) from group variable 
dat.ord.OL <- files.OL %>% 
  map(~read_csv(., na = c("", "NA", "N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(`X Parameter` == "BL1-H", is.na(`Y Parameter`)) %>% 
  select(Replicate, Plate = `Experiment`, Group , Sample, Count, median = `X Median`, peak = `X Peak`,
         sd = `X SD`, cv = `X %CV`, rCV = `X %rCV`) %>% 
  mutate_at("Group", str_replace, "-0Pi", "") %>% 
  mutate_at("Group", str_replace, "MIN", "min") %>%
  mutate(Group = ordered(Group, levels = tp)) %>% 
  arrange(Group) 

treat.fil.OL <- read_csv("input/OL_treatment/OL_tr.csv", na = c("","NA","N/A"), col_types = cols()) %>% 
  select(genotype = `group_name`, Sample, treat)

data.OL.tmp <- left_join(dat.ord.OL, treat.fil.OL, by = c("Sample"))
data.OL <- add_row(data.cb,data.OL.tmp)

```

#MutMsn4 #1 & #2
```{r, Import the Data into R}
files.mutM4 <- dir("input/2_4Imp_gz_merge", pattern = "merge-*") # get the file names of the merged
files.mutM4 <- file.path("input/2_4Imp_gz_merge", files.mutM4)         # this appends the directory to the file names

names(files.mutM4) <- c("Rep1-H2O2", "Rep1-0Pi","Rep2-0Pi", "Rep3-0Pi" ,"Rep2-H2O2", "Rep3-H2O2")

tp <- c("0min", "30min", "60min", "90min", "120min", "150min",  "180min", "210min", "240min") # ordered time points

# import and process the data to the format we want
## remove characters (0Pi-0min; 240mmin) from group variable 
dat.ord.mutM4 <- files.mutM4 %>% 
  map(~read_csv(., na = c("", "NA", "N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(`X Parameter` == "BL1-H", is.na(`Y Parameter`)) %>% 
  select(Replicate, Plate, Group, Sample, Count, median = `X Median`, peak = `X Peak`,
         sd = `X SD`, cv = `X %CV`, rCV = `X %rCV`) %>% 
  mutate_at("Group", str_replace, "0Pi-", "") %>% 
  mutate_at("Group", str_replace, "240m", "240") %>%
  mutate(Group = ordered(Group, levels = tp)) %>% 
  arrange(Group)   
```


```{r, Subset the dataset and merge with the genotype information:}
# get genotype info and petites info
geno <- read.csv("input/Genotype_2_4Imp.csv")
names(geno) <- c("HB_strain", names(geno)[-1])


# get treatment info
tr_files.mutM4 <- dir("input/2_4Imp_treatment", pattern = "d0*")
tr_files.mutM4 <- file.path("input/2_4Imp_treatment", tr_files.mutM4)
names(tr_files.mutM4) <-  c("Rep1-H2O2", "Rep1-0Pi","Rep2-0Pi", "Rep3-0Pi" ,"Rep2-H2O2", "Rep3-H2O2")

#sum(treat.fil$treat == "0Pi")
#sum(treat.fil$treat == "H2O2")

# combine HB_strain info to rule out petites
treat.fil.mutM4 <- tr_files.mutM4 %>% 
  map(~read_csv(., na = c("","NA","N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(!is.na(`group_name`)) %>% 
  select(Replicate, genotype = `group_name`, Sample, treat) %>% 
  left_join(., geno, by = c("genotype", "Sample")) # %>% 
  #subset(!is.na(YPG))


# combine genotype and treat variables into the flow data
data.mutM4 <- left_join(dat.ord.mutM4, treat.fil.mutM4, by = c("Replicate", "Sample")) %>% 
  filter(!is.na(YPG)) %>% 
  select(Replicate,Plate,Group,Sample,genotype,median,treat)
data.OL_mutM4 <- add_row(data.OL,data.mutM4)

# select out 0Pi data
pi.dat.OL_mutM4 <- data.OL_mutM4 %>% 
  filter(treat == "0Pi" & genotype %in% c("wt","MutMsn4 #1","MutMsn4 #2","msn4_ko","4OL")) %>%  
  select(Time = Group, Sample, Plate, replicate = Replicate, genotype, median) %>%
  mutate(.,Genotype = gsub("_ko","",genotype)) %>% 
  mutate(.,new_median =median/1000) %>% 
  mutate(.,new_time = as.numeric(gsub("min","",Time)))%>% 
  arrange(new_time, genotype, replicate)

pi.dat.OL_mutM4.summary <- pi.dat.OL_mutM4 %>% 
  filter(!is.na(new_median)) %>%
  group_by(Genotype,Time) %>% 
  summarise(sd = sd(new_median, na.rm = TRUE), mean_median = mean(new_median)) %>% 
  mutate(.,`Time (min)`= as.numeric(gsub("min","",Time)))
```

```{r}
MutM4_color <- c("#B79F00", "#00BFC4",  "#F8766D", "#00BA38", "#F564E3")

pi.dat.OL_mutM4 %>% 
  subset(., !is.na(new_median)) %>%  
  ggplot(aes(x = new_time, y = new_median, color = Genotype)) + geom_point(size = 0.2) + 
  stat_summary(fun = "mean", geom = "point", size = 2) +
  stat_smooth(aes(x = new_time), se = FALSE) +
  scale_x_continuous(breaks = seq(0,240,30), minor_breaks = seq(0,240,30))+
  theme_bw() +
  theme(legend.position=c(0.18,0.75), legend.background = element_rect(fill = "white", color = "black", size = 1),
        legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.y = element_text(size = 18),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=0,hjust=0.5), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values= MutM4_color)
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-cis-Msn4BS.png"),
   #      width = 7, height = 4,units = 'in', dpi = 300)

pi.dat.OL_mutM4.summary %>%
  ggplot(aes(x = `Time (min)`, y = mean_median, color = Genotype)) + geom_point(size = 0.5) + 
  geom_errorbar(aes(ymin=mean_median-sd, ymax=mean_median+sd), width=3, size = 0.8 ) +
  stat_summary(fun = "mean", geom = "point", size = 2) +
  stat_smooth(aes(x = `Time (min)`), se = FALSE) +
  scale_x_continuous(breaks = seq(0,240,30), minor_breaks = seq(0,240,30))+
  theme_bw() +
  theme(legend.position=c(0.18,0.75), legend.background = element_rect(fill = "white", color = "black", size = 1),
        legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_text(size = 18),
        axis.text.x = element_text(angle=0,hjust=0.5), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values= MutM4_color)
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-sd-cis-Msn4BS-kos.png"),
   #      width = 7, height = 5,units = 'in', dpi = 300) 

  
#library(scales)
#show_col(hue_pal()(5))
#show_col(hue_pal()(6))
```

box plot + dot plot for trans TF kos CTA1-GFP
```{r}
pi.MutM4_OL.tp <- pi.dat.OL_mutM4 %>% 
  filter(Time %in% c("0min", "240min" ) & !is.na(median))


pi.MutM4_OL.tp %>% 
  mutate(Genotype = factor(Genotype, levels = c("wt", "msn4", "4OL", "MutMsn4 #1", "MutMsn4 #2"))) %>% 
  ggplot(aes(x=Genotype, y=new_median, color = Time)) +
  geom_point(aes(x = Genotype, y = new_median), position = position_jitterdodge(jitter.width = 1)) +
  theme_bw() +
  theme(legend.position=c(0.4,0.85), legend.background = element_rect(fill = "white", color = "black", size = 1), legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=30,hjust = 1, vjust = 1), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  stat_summary(aes(group = Time), fun = "median", geom = "point", 
               color = "gray50", position = position_dodge()) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values = c("0min" = "#999999", "240min" = "#F564E3"))
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-cis-2-4Imp-tp.png"),
   #      width = 7, height = 5,units = 'in', dpi = 300)
  
           
```

#MutSkn7 #1 & #2
```{r, Import the Data into R}
files.mutS7 <- dir("input/6_8Imp_gz_merge", pattern = "merge-*") # get the file names of the merged
files.mutS7 <- file.path("input/6_8Imp_gz_merge", files.mutS7)         # this appends the directory to the file names

names(files.mutS7) <- c("Rep1-H2O2", "Rep1-0Pi","Rep2-0Pi", "Rep3-0Pi" ,"Rep2-H2O2", "Rep3-H2O2")

tp <- c("0min", "30min", "60min", "90min", "120min", "150min",  "180min", "210min", "240min") # ordered time points

# import and process the data to the format we want
## remove characters (0Pi-0min; 240mmin) from group variable 
dat.ord.mutS7 <- files.mutS7 %>% 
  map(~read_csv(., na = c("", "NA", "N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(`X Parameter` == "BL1-H", is.na(`Y Parameter`)) %>% 
  select(Replicate, Plate, Group, Sample, Count, median = `X Median`, peak = `X Peak`,
         sd = `X SD`, cv = `X %CV`, rCV = `X %rCV`) %>% 
  mutate_at("Group", str_replace, "-H2O2", "") %>% 
  mutate_at("Group", str_replace, "MIN", "min") %>%
  mutate(Group = ordered(Group, levels = tp)) %>% 
  arrange(Group)   
```


```{r, Subset the dataset and merge with the genotype information:}
# get genotype info and petites info
geno.mutS7 <- read.csv("input/Genotype_6_8Imp.csv")
names(geno.mutS7) <- c("HB_strain", names(geno)[-1])

# get treatment info
tr_files.mutS7 <- dir("input/6_8Imp_treatment", pattern = "d0*")
tr_files.mutS7 <- file.path("input/6_8Imp_treatment", tr_files.mutS7)
names(tr_files.mutS7) <-  c("Rep1-H2O2", "Rep1-0Pi","Rep2-0Pi", "Rep3-0Pi" ,"Rep2-H2O2", "Rep3-H2O2")


# combine HB_strain info to rule out petites
treat.fil.mutS7 <- tr_files.mutS7 %>% 
  map(~read_csv(., na = c("","NA","N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(!is.na(`group_name`)) %>% 
  select(Replicate, genotype = `group_name`, Sample, treat) %>% 
  left_join(., geno.mutS7, by = c("genotype", "Sample")) # %>% 
  #subset(!is.na(YPG))


# combine genotype and treat variables into the flow data
data.mutS7 <- left_join(dat.ord.mutS7, treat.fil.mutS7, by = c("Replicate", "Sample")) %>% 
  filter(!is.na(YPG)) %>% 
  select(Replicate,Plate,Group,Sample,genotype,median,treat)

data.OL_mutS7 <- add_row(data.OL,data.mutS7)


# select out 0Pi data
pi.dat.OL_mutS7 <- data.OL_mutS7 %>% 
  filter(treat == "0Pi" & genotype %in% c("wt","MutS7#1","MutS7#2","8OL","skn7_ko")) %>%  
  select(Time = Group, Sample, Plate, replicate = Replicate, genotype, median) %>%
  mutate(.,Genotype = gsub("_ko","",genotype)) %>% 
  mutate(.,new_median =median/1000) %>% 
  mutate(.,new_time = as.numeric(gsub("min","",Time)))%>% 
  arrange(new_time, genotype, replicate)

pi.dat.OL_mutS7.summary <- pi.dat.OL_mutS7 %>% 
  filter(!is.na(new_median)) %>%
  group_by(Genotype,Time) %>% 
  summarise(sd = sd(new_median, na.rm = TRUE), mean_median = mean(new_median)) %>% 
  mutate(.,`Time (min)`= as.numeric(gsub("min","",Time)))
```

```{r}
MutS7_color <- c("#B79F00", "#00BFC4",  "#F8766D", "#619CFF", "#F564E3")

pi.dat.OL_mutS7 %>% 
  subset(., !is.na(new_median)) %>%  
  ggplot(aes(x = new_time, y = new_median, color = Genotype)) + geom_point(size = 0.2) + 
  stat_summary(fun = "mean", geom = "point", size = 2) +
  stat_smooth(aes(x = new_time), se = FALSE) +
  scale_x_continuous(breaks = seq(0,240,30), minor_breaks = seq(0,240,30))+
  theme_bw() +
  theme(legend.position="right", legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=0,hjust=0.5), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values= MutS7_color)
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-cis-Skn7BS.png"),
   #      width = 7, height = 4,units = 'in', dpi = 300)

pi.dat.OL_mutS7.summary %>%
  ggplot(aes(x = `Time (min)`, y = mean_median, color = Genotype)) + geom_point(size = 0.5) + 
  geom_errorbar(aes(ymin=mean_median-sd, ymax=mean_median+sd), width=3, size = 0.8 ) +
  stat_summary(fun = "mean", geom = "point", size = 2) +
  stat_smooth(aes(x = `Time (min)`), se = FALSE) +
  scale_x_continuous(breaks = seq(0,240,30), minor_breaks = seq(0,240,30))+
  theme_bw() +
  theme(legend.position=c(0.18,0.75), legend.background = element_rect(fill = "white", color = "black", size = 1),
        legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_text(size = 18),
        axis.text.x = element_text(angle=0,hjust=0.5), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values= MutS7_color)
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-sd-cis-Skn7BS.png"),
   #      width = 7, height = 5,units = 'in', dpi = 300) 


  
#library(scales)
#show_col(hue_pal()(5))
#show_col(hue_pal()(6))
```

```{r}
pi.MutS7_OL.tp <- pi.dat.OL_mutS7 %>% 
  filter(Time %in% c("0min", "240min" ) & !is.na(median))


pi.MutS7_OL.tp %>% 
  mutate(Genotype = factor(Genotype, levels = c("wt", "skn7", "8OL", "MutS7#1", "MutS7#2"))) %>% 
  ggplot(aes(x=Genotype, y=new_median, color = Time)) +
  geom_point(aes(x = Genotype, y = new_median), position = position_jitterdodge(jitter.width = 1)) +
  theme_bw() +
  theme(legend.position=c(0.4,0.85), legend.background = element_rect(fill = "white", color = "black", size = 1), legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=30,hjust = 1, vjust = 1), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  stat_summary(aes(group = Time), fun = "median", geom = "point", 
               color = "gray50", position = position_dodge()) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values = c("0min" = "#999999", "240min" = "#F564E3"))
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-cis-6-8Imp-tp.png"),
   #      width = 7, height = 5,units = 'in', dpi = 300)
```

# combine MutS7 & Mut Msn4 BS data
```{r}
data.OL_cb <- add_row(data.OL_mutM4,data.mutS7)

pi.dat.OL_cb <- data.OL_cb %>% 
  filter(treat == "0Pi" & genotype %in% c("wt","MutS7#1","MutS7#2","8OL","skn7_ko","MutMsn4 #1","MutMsn4 #2","msn4_ko","4OL")) %>%  
  select(Time = Group, Sample, Plate, replicate = Replicate, genotype, median) %>%
  mutate(.,Genotype = gsub("_ko","",genotype)) %>% 
  mutate(.,new_median =median/1000) %>% 
  mutate(.,new_time = as.numeric(gsub("min","",Time)))%>% 
  arrange(new_time, genotype, replicate)

pi.OL.tp <- pi.dat.OL_cb %>% 
  filter(Time %in% c("0min", "240min" ) & !is.na(median))


pi.OL.tp %>% 
  mutate(Genotype = factor(Genotype, levels = c("wt","4OL","msn4","MutMsn4 #1","MutMsn4 #2", "8OL", "skn7","MutS7#1", "MutS7#2"))) %>% 
  ggplot(aes(x=Genotype, y=new_median, color = Time)) +
  geom_point(aes(x = Genotype, y = new_median), position = position_jitterdodge(jitter.width = 1)) +
  theme_bw() +
  theme(legend.position=c(0.25,0.85), legend.background = element_rect(fill = "white", color = "black", size = 1), 
        legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=30,hjust = 1, vjust = 1), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  stat_summary(aes(group = Time), fun = "median", geom = "point", 
               color = "gray50", position = position_dodge()) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values = c("0min" = "#999999", "240min" = "#F564E3"))
#  ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-cis-all-tp.png"),
 #        width = 10, height = 5,units = 'in', dpi = 300)
           
```

