---
title: "rim15_ko"
author: "JY"
date: "11/5/2022"
output: html_document
---
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(mgcv)
library(broom)
```



```{r, Import the Data into R}
files.r15 <- dir("input/rim15_gz_merge", pattern = "merge-*") # get the file names of the merged
files.r15 <- file.path("input/rim15_gz_merge", files.r15)         # this appends the directory to the file names
#names(files) <- paste0("Rep", 1:3)        # name the replicates

names(files.r15) <- c("Rep1-0Pi-Ctrl","Rep2-0Pi-Ctrl", "Rep3-0Pi-Ctrl") # correspond to treatment files

tp <- c("0min",  "30min", "60min", "90min", "120min", "150min",  "180min", "210min", "240min") # ordered time points

# import and process the data to the format we want
dat.ord.r15 <- files.r15 %>% 
  map(~read_csv(., na = c("", "NA", "N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(`X Parameter` == "BL1-H", is.na(`Y Parameter`)) %>% 
  select(Replicate, Plate, Group, Sample, Count, median = `X Median`, peak = `X Peak`,
         sd = `X SD`, cv = `X %CV`, rCV = `X %rCV`) %>% 
  mutate(Group = ordered(Group, levels = tp)) %>% 
  arrange(Group)

#write_csv(dat.ord, file = "input/rim15_gz_merge/2021014-1019-rim15-KO-flow-data.csv")
```


```{r, Subset the dataset and merge with the genotype information:}
# get genotype info
tr_files.r15 <- dir("input/rim15_treatment", pattern = "d0*")
tr_files.r15 <- file.path("input/rim15_treatment", tr_files.r15)
names(tr_files.r15) <- c("Rep1-0Pi-Ctrl","Rep2-0Pi-Ctrl", "Rep3-0Pi-Ctrl")


treat.fil.r15 <- tr_files.r15 %>% 
  map(~read_csv(., na = c("","NA","N/A"), col_types = cols())) %>% 
  bind_rows(.id = "Replicate") %>% 
  filter(!is.na(`group_name`)) %>% 
  select(Replicate, genotype = `group_name`, Sample, treat)

# combine genotype and treat variables into the flow data
data.r15 <- left_join(dat.ord.r15, treat.fil.r15, by = c("Replicate", "Sample"))
#sum(is.na(data$Group))

#write_csv(data, file = "gz_merge/20210724-0805-treat-gt-Rim15-KO-flow-data.csv.gz")

# select out 0Pi data
pi.dat.r15 <- data.r15 %>% 
  filter(treat == "0Pi" & genotype %in% c("wt","msn4_nat_ko","rim15_ko","msn4rim15_ko")) %>%  
  select(Time = Group, Sample, Plate, replicate = Replicate, genotype, median) %>%
  mutate(.,Genotype = gsub("_ko","",genotype)) %>% 
  mutate(.,new_median =median/1000) %>% 
  mutate(.,new_time = as.numeric(gsub("min","",Time)))%>% 
  mutate(.,Genotype = gsub("_nat","",Genotype)) %>% 
  arrange(new_time, genotype, replicate) 

pi.dat.r15.summary <- pi.dat.r15 %>% 
  filter(!is.na(new_median)) %>%
  group_by(Genotype,Time) %>% 
  summarise(sd = sd(new_median, na.rm = TRUE), mean_median = mean(new_median)) %>% 
  mutate(.,`Time (min)`= as.numeric(gsub("min","",Time)))

```

```{r, visualize the data}
genotype_color <- c("#00BFC4","#B79F00","#619CFF", "#F564E3") 

pi.dat.r15 %>% 
  filter(!is.na(new_median)) %>% 
  ggplot(aes(x = new_time, y = new_median, color = Genotype)) + geom_point(size = 0.2) + 
  stat_summary(fun = "mean", geom = "point", size = 2) +
  stat_smooth(aes(x = new_time), se = FALSE) +
  scale_x_continuous(breaks = seq(0,240,30), minor_breaks = seq(0,240,30))+
  theme_bw() +
  theme(legend.position=c(0.15,0.72), legend.background = element_rect(fill = "white", color = "black", size = 1),
        legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle=0,hjust=0.5), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values= genotype_color)
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-trans-rim15-kos.png"),
   #      width = 7, height = 4,units = 'in', dpi = 300)

#library(scales)
#show_col(hue_pal()(5))
#show_col(hue_pal()(6))

pi.dat.r15.summary %>%
  ggplot(aes(x = `Time (min)`, y = mean_median, color = Genotype)) + geom_point(size = 0.5) + 
  geom_errorbar(aes(ymin=mean_median-sd, ymax=mean_median+sd), width=3, size = 0.8 ) +
  stat_summary(fun = "mean", geom = "point", size = 2) +
  stat_smooth(aes(x = `Time (min)`), se = FALSE) +
  scale_x_continuous(breaks = seq(0,240,30), minor_breaks = seq(0,240,30))+
  theme_bw() +
  theme(legend.position=c(0.18,0.75), legend.background = element_rect(fill = "white", color = "black", size = 1),
        legend.box = "vertical", legend.text = element_text(size=18), 
        legend.title = element_text(size = 18),
        axis.title = element_text(size = 18), 
        axis.title.x = element_text(size = 18),
        axis.text.x = element_text(angle=0,hjust=0.5), axis.text = element_text(size = 18), 
        plot.title = element_text(size = 18, hjust = 0)) + 
  labs(y = "Cta1-GFP protein level (a.u.)") +
  scale_color_manual(values= genotype_color)
  #ggsave(paste0("./output/", gsub("-", "", Sys.Date()), "-sd-trans-rim15-kos.png"),
   #      width = 7, height = 5,units = 'in', dpi = 300)  
  
#library(scales)
#show_col(hue_pal()(5))
show_col(hue_pal()(6))
```