---
title: "Bin_code_adpt"
author: "Jinye Liang"
date: "August 12, 2022"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(mgcv)
library(broom)
library(viridis)
```

```{r}
asr_raw <- read.csv("../input/MOPO_Sc_Cg_ASR_scatter_plot_d122422.csv")

# scatterplot of MO/MM vs PO/PM
#png("../output/MO_vs_PO.png", width = 4, height = 4, units = 'in',res = 300) # png for slides
asr_raw  %>% subset(., MO.MM != 1 & PO.PM != 1) %>%
  ggplot(aes(x = MO.MM, y = PO.PM)) + 
  geom_point(aes(color = Strain),size = 2) + 
  geom_smooth(aes(color = Strain)) +  # fit to a loess model with 95% CI 
  #geom_smooth(aes(color = Strain, fill = Strain), method = "lm") +
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_y_continuous(labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_x_continuous(labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  # change the scale of x and y axis
  coord_fixed(ratio = 1, xlim = c(0,0.4), ylim = c(0,0.4), expand = TRUE, clip = "on") +
  geom_abline(slope = 1, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("PO/PM") +
  xlab("MO/MM") +
  ggtitle("PO/PM vs MO/MM")


# scatterplot of MO/MM vs PO/PM
asr_raw  %>% subset(., MO.MM != 1 & PO.PM != 1) %>%
  ggplot(aes(x = MO.MM, y = PO.PM)) + 
  geom_point(aes(color = Strain),size = 2) + 
  #geom_smooth(aes(color = Strain)) +  # fit to a loess model with 95% CI 
  #geom_smooth(aes(color = Strain, fill = Strain), method = "lm") +
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_y_continuous(labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_x_continuous(labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  # change the scale of x and y axis
  coord_fixed(ratio = 1, xlim = c(0,0.4), ylim = c(0,0.4), expand = TRUE, clip = "on") +
  geom_abline(slope = 1, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("PO/PM") +
  xlab("MO/MM") +
  ggtitle("PO/PM vs MO/MM")
#  ggsave("../output/MO_vs_PO_HT.png", width = 4, height = 4, units = 'in',dpi = 300)
  
# scatterplot of MO/MM vs PO/PM
asr_raw  %>% subset(., Strain != "Kl" & MO.MM != 1 & PO.PM != 1) %>%
  ggplot(aes(x = MO.MM, y = PO.PM)) + 
  geom_point(aes(color = Strain),size = 2) + 
  #geom_smooth(aes(color = Strain)) +  # fit to a loess model with 95% CI 
  #geom_smooth(aes(color = Strain, fill = Strain), method = "lm") +
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_y_continuous(labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_x_continuous(labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  # change the scale of x and y axis
  coord_fixed(ratio = 1, xlim = c(0,0.4), ylim = c(0,0.4), expand = TRUE, clip = "on") +
  geom_abline(slope = 1, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("PO/PM") +
  xlab("MO/MM") +
  ggtitle("PO/PM vs MO/MM")
#  ggsave("../output/MO_vs_PO_ScCg_HT_d122422.png", width = 4, height = 4, units = 'in',dpi = 300)
  
# scatterplot of MO/MM vs PO/PM
asr_raw  %>% subset(., Strain != "Kl" & Experimenter == "JL" & MO.MM != 1 & PO.PM != 1) %>%
  ggplot(aes(x = MO.MM, y = PO.PM)) + 
  geom_point(aes(color = Strain),size = 2) + 
  #geom_smooth(aes(color = Strain)) +  # fit to a loess model with 95% CI 
  #geom_smooth(aes(color = Strain, fill = Strain), method = "lm") +
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_y_continuous(labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_x_continuous(labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  # change the scale of x and y axis
  coord_fixed(ratio = 1, xlim = c(0,0.4), ylim = c(0,0.4), expand = TRUE, clip = "on") +
  geom_abline(slope = 1, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("PO/PM") +
  xlab("MO/MM") +
  ggtitle("PO/PM vs MO/MM")
#  ggsave("../output/d122422_MO_vs_PO.png", width = 4, height = 4, units = 'in',dpi = 300)

```

```{r}
# MO/MM vs ASR Score
asr_raw %>% mutate(.,ASR_Score = PO.PM/MO.MM, .keep = "all") %>% subset(., Strain != "Kl" & MO.MM != 1 & ASR_Score != 1) %>%
  ggplot(aes(x = MO.MM, y = ASR_Score)) + 
  geom_point(aes(color = Strain),size = 2) + 
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_x_continuous(labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  # change the scale of x and y axis
  coord_fixed(ratio = 0.01, xlim = c(0,0.4), ylim = c(0,40), expand = TRUE, clip = "on") +
  geom_abline(slope = 0, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("ASR_Score") +
  xlab("MO/MM") +
  ggtitle("ASR effect vs MO/MM")
#  ggsave("../output/ASR_vs_MOvsMM.png", width = 4, height = 4, units = 'in',dpi = 300)

# MO/MM vs ASR Score with loess fit
asr_raw %>% mutate(.,ASR_Score = PO.PM/MO.MM, .keep = "all") %>% subset(.,Strain != "Kl") %>% subset(., MO.MM != 1 & ASR_Score != 1) %>%
  ggplot(aes(x = MO.MM, y = ASR_Score)) + 
  geom_point(aes(color = Strain),size = 2) + 
  #geom_smooth(aes(color = Strain),span = 1) + # fit to a loess model with 95% CI 
  #geom_smooth(aes(color = Strain, fill = Strain), method = "lm") +
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_y_continuous(trans = "log10")+
  scale_x_reverse(lim = c(0.3,0), labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  #scale_x_reverse() +
  # change the scale of x and y axis
  #coord_fixed(ratio = 0.01, xlim = c(0,0.4), ylim = c(0,40), expand = TRUE, clip = "on") +
  coord_fixed(ratio = 0.1,xlim = c(0.3,0),ylim = c(0.3,30)) +
  geom_abline(slope = 0, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("ASR_Score") +
  xlab("MO/MM") +
  ggtitle("ASR effect vs MO/MM")
#  ggsave("../output/ASR_vs_MOvsMM_rev_x_logy.png", width = 4, height = 4, units = 'in',dpi = 300)
  
# MO/MM vs ASR Score with loess fit
asr_raw %>% mutate(.,ASR_Score = PO.PM/MO.MM, .keep = "all") %>% subset(., MO.MM != 1 & ASR_Score != 1) %>%
  ggplot(aes(x = MO.MM, y = ASR_Score)) + 
  geom_point(aes(color = Strain),size = 2) + 
  #geom_smooth(aes(color = Strain),span = 1) + # fit to a loess model with 95% CI 
  #geom_smooth(aes(color = Strain, fill = Strain), method = "lm") +
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_y_continuous(trans = "log10")+
  scale_x_reverse(lim = c(0.3,0), labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  #scale_x_reverse() +
  # change the scale of x and y axis
  #coord_fixed(ratio = 0.01, xlim = c(0,0.4), ylim = c(0,40), expand = TRUE, clip = "on") +
  coord_fixed(ratio = 0.1,xlim = c(0.3,0),ylim = c(0.3,30)) +
  geom_abline(slope = 0, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("ASR_Score") +
  xlab("MO/MM") +
  ggtitle("ASR effect vs MO/MM")
#  ggsave("../output/ASR_vs_MOvsMM_rev_x_logy_KL.png", width = 4, height = 4, units = 'in',dpi = 300)

# MO/MM vs ASR Score with loess fit
asr_raw %>% mutate(.,ASR_Score = PO.PM/MO.MM, .keep = "all") %>% subset(., Strain != "Kl" & MO.MM != 1 & ASR_Score != 1) %>%
  ggplot(aes(x = MO.MM, y = ASR_Score)) + 
  geom_point(aes(color = Strain),size = 2) + 
  #geom_smooth(aes(color = Strain),span = 1) + # fit to a loess model with 95% CI 
  #geom_smooth(aes(color = Strain, fill = Strain), method = "lm") +
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_y_continuous(trans = "log10")+
  scale_x_reverse(lim = c(0.3,0), labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  #scale_x_reverse() +
  # change the scale of x and y axis
  #coord_fixed(ratio = 0.01, xlim = c(0,0.4), ylim = c(0,40), expand = TRUE, clip = "on") +
  coord_fixed(ratio = 0.1,xlim = c(0.3,0),ylim = c(0.3,30)) +
  geom_abline(slope = 0, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("ASR_Score") +
  xlab("MO/MM") +
  ggtitle("ASR effect vs MO/MM")
#  ggsave("../output/ASR_vs_MOvsMM_rev_x_logy.png", width = 4, height = 4, units = 'in',dpi = 300)

# MO/MM vs ASR Score with loess fit
asr_raw %>% mutate(.,ASR_Score = PO.PM/MO.MM, .keep = "all") %>% subset(., Experimenter == "JL", Strain != "Kl" & MO.MM != 1 & ASR_Score != 1) %>%
  ggplot(aes(x = MO.MM, y = ASR_Score)) + 
  geom_point(aes(color = Strain),size = 2) + 
  #geom_smooth(aes(color = Strain),span = 1) + # fit to a loess model with 95% CI 
  #geom_smooth(aes(color = Strain, fill = Strain), method = "lm") +
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_y_continuous(trans = "log10")+
  scale_x_reverse(lim = c(0.3,0), labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  #scale_x_reverse() +
  # change the scale of x and y axis
  #coord_fixed(ratio = 0.01, xlim = c(0,0.4), ylim = c(0,40), expand = TRUE, clip = "on") +
  coord_fixed(ratio = 0.1,xlim = c(0.3,0),ylim = c(0.3,30)) +
  geom_abline(slope = 0, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("ASR_Score") +
  xlab("MO/MM") +
  ggtitle("ASR effect vs MO/MM")
#  ggsave("../output/d122422_ASR_vs_MOvsMM_rev_x_logy_JL.png", width = 4, height = 4, units = 'in',dpi = 300)


# MO/MM vs ASR Score for Cg
asr_raw %>% subset(.,Strain == "Cg") %>% mutate(.,ASR_Score = PO.PM/MO.MM, .keep = "all") %>% subset(., MO.MM != 1 & ASR_Score != 1) %>%
  ggplot(aes(x = MO.MM, y = ASR_Score)) + 
  geom_point(aes(color = Strain),size = 2) + 
  #geom_smooth(aes(color = Strain),span = 1) + # fit to a loess model with 95% CI 
  #geom_smooth(aes(color = Strain, fill = Strain), method = "lm") +
  #scale_color_viridis(discrete = TRUE, option = "D") +
  #scale_fill_viridis(discrete = TRUE) + 

  # change decimal scale to pct
  scale_y_continuous(trans = "log10")+
  scale_x_reverse(lim = c(0.3,0), labels = scales::percent, breaks = seq(0, 0.4, 0.1)) +
  scale_color_manual(values = c("grey", "deeppink3", "hotpink", "darkorchid2", "deepskyblue", "dodgerblue3", "grey20", "seagreen1"))  +
  #scale_x_reverse() +
  # change the scale of x and y axis
  #coord_fixed(ratio = 0.01, xlim = c(0,0.4), ylim = c(0,40), expand = TRUE, clip = "on") +
  coord_fixed(ratio = 0.1,xlim = c(0.3,0),ylim = c(0.3,30)) +
  geom_abline(slope = 0, intercept = 0, color="wheat2", linetype="dashed", size=1) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  ylab("ASR_Score") +
  xlab("Severity of the secondary stress") +
  ggtitle("ASR effect vs MO/MM")
 # ggsave("../output/Cg_ASR_vs_MOvsMM_rev_x_logy.png", width = 4, height = 4, units = 'in',dpi = 300)  
  
  
```

# plot the comparable MO data at 100mM and 10mM for Cg and Sc
# do the statistical test
```{r}
mo_comp <- asr_raw %>% filter(H2O2 %in% c("100mM","10mM"))
mo_comp %>% ggplot(aes(x = Strain, y = MO.MM_percent)) + geom_point(size =5, alpha = 0.5) +
  theme_bw() +
  theme(axis.text.x=element_text(hjust=1)) +
  ylab("Survival Rate % (MO/MM)") +
  xlab("Strain")
# ggsave("../output/Cg100_Sc10.png", width = 4, height = 4, units = 'in',dpi = 300) 


# test for homogeneity in variance
res.ftest <- var.test(MO.MM_percent ~ Strain, data = mo_comp)
res.ftest
## There is no significant difference between the variances of the two sets of data. Therefore, we can use the classic t-test witch assume equality of the two variances.

# paired t-test
res <- t.test(MO.MM_percent ~ Strain, data = mo_comp, paired = TRUE, var.equal = TRUE)
res
## no significant difference in the survival rate of 100mM treated Cg and 10mM treated Sc
```

# Fold increase in survival relative to the primary stress (CFU data for Cg and Sc)
```{r}
asr_dot <- asr_raw %>% filter(H2O2 %in% c("20mM","40mM","60mM","80mM","100mM","2mM","4mM","6mM","8mM","10mM") & !(Strain %in% c("Kl"))) %>% mutate(H2O2_con = as.numeric(gsub("mM","",H2O2)))

# Cg CFU
asr_dot %>% filter(Strain == "Cg") %>% 
  ggplot(aes(x = H2O2_con, y = ASR_score)) + geom_point(dotsize = 5, alpha = 0.5) + 
  scale_y_continuous(limits = c(0, 33)) +
  theme_bw() +
  theme(axis.text.x=element_text(hjust=1)) +
  ylab("ASR Score (r'/r)") +
  xlab("H2O2 conc. (mM)")
 ggsave("../output/Cg_ASR_grad_CFU.png", width = 4, height = 4, units = 'in',dpi = 300) 

# Sc CFU
asr_dot %>% filter(Strain == "Sc") %>% 
  ggplot(aes(x = H2O2_con, y = ASR_score)) + geom_point(dotsize = 5, alpha = 0.5) + 
  scale_y_continuous(limits = c(0, 33)) +
  theme_bw() +
  theme(axis.text.x=element_text(hjust=1)) +
  ylab("ASR Score (r'/r)") +
  xlab("H2O2 conc. (mM)")
 ggsave("../output/Sc_ASR_grad_CFU.png", width = 4, height = 4, units = 'in',dpi = 300) 

# combine the Cg and Sc onto the same plot
asr_dot %>%
  ggplot(aes(x = H2O2_con, y = ASR_score)) + geom_point(aes(color = Strain),dotsize = 5, alpha = 0.5) + 
  scale_y_continuous(limits = c(0, 33)) +
  theme_bw() +
  theme(axis.text.x=element_text(hjust=1)) +
  ylab("ASR Score (r'/r)") +
  xlab("H2O2 conc. (mM)")

```

# Fold increase in survival relative to the primary stress (spotting assay density data for Cg and Sc)
```{r}
spot_asr <-  read.csv("../input/spotting_assay_density.csv")

# Cg spotting assay
spot_asr %>% filter(Strain == "Cg") %>% 
  ggplot(aes(x = H2O2_mM, y = ASR_Score)) + geom_point(dotsize = 3, alpha = 0.5) +  
  scale_y_continuous(limits = c(0, 60)) +
  theme_bw() +
  theme(axis.text.x=element_text(hjust=1)) +
  ylab("ASR Score (r'/r)") +
  xlab("H2O2 conc. (mM)")
 ggsave("../output/Cg_ASR_grad_spot.png", width = 4, height = 4, units = 'in',dpi = 300) 

# Sc spotting
spot_asr %>% filter(Strain == "Sc") %>% 
  ggplot(aes(x = H2O2_mM, y = ASR_Score)) + geom_point(dotsize = 3, alpha = 0.5) +  
  scale_y_continuous(limits = c(0, 10)) +
  theme_bw() +
  theme(axis.text.x=element_text(hjust=1)) +
  ylab("ASR Score (r'/r)") +
  xlab("H2O2 conc. (mM)")
 ggsave("../output/Sc_ASR_grad_spot.png", width = 4, height = 4, units = 'in',dpi = 300) 


# combine Cg and Sc
spot_asr %>% ggplot(aes(x = H2O2_mM, y = ASR_Score)) + geom_point(aes(color = Strain), dotsize = 3, alpha = 0.5) + 
  scale_y_continuous(limits = c(0, 60)) +
  theme_bw() +
  theme(axis.text.x=element_text(hjust=1)) +
  ylab("ASR Score (r'/r)") +
  xlab("H2O2 conc. (mM)")

  

```

# ASR Score vs different length of the primary stress treatment (CFU data)
```{r}
time_asr <- read.csv("../input/Time_course_ASR.csv")

time_asr %>%  ggplot(aes(x = Time_min, y = ASR_Score)) + geom_point(aes(color = Strain), dotsize = 5, alpha = 0.5) +
    scale_x_continuous(minor_breaks = seq(0,135,by=45),
                     breaks = seq(0,135,by=45),
                     limits = c(40,140),
                     expand = c(0,0)) +
  scale_y_continuous(limits = c(0, 250)) +
  theme_bw() +
  theme(axis.text.x=element_text(hjust=1)) +
  ylab("ASR Score (r'/r)") +
  xlab("Time (min)")
 ggsave("../output/timecourse_asr.png", width = 4, height = 4, units = 'in',dpi = 300) 

# transformed the y axis
time_asr %>%  ggplot(aes(x = Time_min, y = ASR_Score)) + geom_point(aes(color = Strain), dotsize = 5, alpha = 0.5) +
    scale_x_continuous(minor_breaks = seq(0,135,by=45),
                     breaks = seq(0,135,by=45),
                     limits = c(40,140),
                     expand = c(0,0)) +
  scale_y_continuous(trans = 'log10',limits = c(0.1, 250)) +
  theme_bw() +
  theme(axis.text.x=element_text(hjust=1)) +
  ylab("ASR Score (r'/r)") +
  xlab("Time (min)")

```



